- name: Getting data from routers

  hosts: routers
  
#  vars:
#    ansible_ssh_private_key_file: /home/ubuntu-admin/.ssh/id_rsa

  gather_facts: false

  tasks:

    - name: system command

      routeros_command:

        commands: /ip dhcp-client print value-list

      register: system_print

    - name: debug print

      debug: var=system_print.stdout_lines
