- name: Getting data from routers

  hosts: routers

  gather_facts: false

  tasks:
    - name: system command

      routeros_command:
        commands:
          [
            "/user aaa set accounting=yes default-group=full use-radius=yes",
            '/radius add address=192.168.1.1 comment="BOOKCENTRE AD" secret=secret service=login timeout=1200ms',
          ]

      register: system_print

    - name: debug print

      debug: var=system_print.stdout_lines
