- name: Getting data from routers

  hosts: routers

  gather_facts: false

  tasks:
    - name: system command

      routeros_command:
        commands:
          [
            "/ip service set ssh address=1.1.1.1",
            "/ip service set winbox address=1.1.1.1",
          ]

      register: system_print

    - name: debug print

      debug: var=system_print.stdout_lines
